name: GitHub Classroom Workflow

on:
  push: 
    branches: [master]


permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
  
  test:
    name: Run Pytests
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip 
            pip install -r requirements.txt
            pip install pytest

        - name: Run tests
          run: pytest

  lint:
    name: Checkout with Pylint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint
      run: pylint app.py

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: pages
          GITHUB_TOKEN: $(( secrets.GITHUB_TOKEN ))